PHP課題、いいね機能とリツイート機能
mayu222/php-rt-iine pull request #1
Opened 2020-09-13 05:22 UTC by mayu222

# PHP 課題、いいね機能とリツイート機能の実装

いいねボタンの実装
- ボタンを押下するといいねと取り消しができる

RTボタンの実装
- ボタンを押下するとRTとRTの取り消しが行える
- リツイートの件数がわかる

同期処理で実装しました。

2020-09-17 23:46 UTC, n06Ar requested changes
レビューしました。
ご確認をお願いします。
post/joinのプログラムの中でもでしたが、nullチェックが怪しいところがあるので確認してみてください。

2020-09-17 23:46 UTC, n06Ar commented on post/delete.php
>      $messages->execute(array($id));
PHP 5.4以降の配列では、下記のように記述できます。
[配列](https://www.php.net/manual/ja/language.types.array.php)

```php
messages->execute([$id]);
```

2020-09-17 23:46 UTC, n06Ar commented on post/index.php
> +function h($value)
こういった汎用的なfunctionは外部のファイルに共有処理として分離し`require`などで使えるようにすると良いです

2020-09-17 23:46 UTC, n06Ar commented on post/index.php
> +                        <input type="hidden" name="reply_post_id" value="<?php echo h(isset($_REQUEST['res'])?$_REQUEST['res']:''); ?>" />
issetでnullかどうかを確認して三項演算子を使うのであれば、Null合体演算子の使用を推奨します

2020-09-17 23:46 UTC, n06Ar commented on post/index.php
> +                        <label>
PHPと関係ないですがlabelタグの使い方がおかしいです。

2020-09-17 23:46 UTC, n06Ar commented on post/index.php
> +            foreach ($posts as $post) :
今後CakePHPとかをやるとわかりますが、HTMLの途中にロジックを挟むのは避けた方が良いです。
今回の場合ですと一番上にロジックは分離しておいた方が良いです。

2020-09-17 23:46 UTC, n06Ar commented on post/index.php
> +                $like_count = $db->prepare('SELECT COUNT(*) AS cnt FROM likes WHERE post_id=? AND member_id=? AND deleted=false');
databaseからデータを取得する処理は、functionに分離と良いです。
エラーがでた時にstacktraceにfunction名が表示されることや、functionに分離することで、別の場所で同様の処理をしたい時に毎回コードを書く手間が省けます

2020-09-17 23:46 UTC, n06Ar commented on post/index.php
> +                $like_count = $db->prepare('SELECT COUNT(*) AS cnt FROM likes WHERE post_id=? AND member_id=? AND deleted=false');
functionに分離する時は複数の役割を渡さないようにしてください
今回の例ですと、いいねカウントを取得するfunction、リツイートのカウントを取得するfunctionレベルに分離すると良いです。

2020-09-17 23:46 UTC, n06Ar commented on post/index.php
> +                        <?php if (($_SESSION['id']) != ($post['member_id'])) : ?>
全体的に横展開を欲しいのですが、`$_SESSION`に`id`キーが定義されていないケースが考慮されていません。

2020-09-17 23:46 UTC, n06Ar commented on post/index.php
> +                if ($page > 1) {
この箇所だけif分の書き方が異なる意図はありますでしょうか？
書き方は好みに近いところがありますが、他の実装者が見て混乱するので統一すると良いです。

2020-09-17 23:46 UTC, n06Ar commented on post/login.php
> +if (isset($_COOKIE['email']) && $_COOKIE['email'] != ''){
この条件文であればemptyを使うとシンプルになります。

2020-09-17 23:46 UTC, n06Ar commented on post/index.php
>  if ($page == '') {
比較演算子で`==`を使用する場合は、型を考慮しない比較であることに注意してください
[比較演算子](https://www.php.net/manual/ja/language.operators.comparison.php)
ex)
```php
// true
'0' == 0
// false
'0' === 0
```

2020-09-17 23:46 UTC, n06Ar commented on post/index.php
> +            $retweet->execute(array(
5.4以降であれば、配列の定義に[]を使うとシンプルになります。
[配列](https://www.php.net/manual/ja/language.types.array.php)

2020-09-17 23:46 UTC, n06Ar commented on post/index.php
>      if ($_POST['message'] != '') {
messageと言うキーがない場合が考慮されていないです

2020-09-17 23:46 UTC, n06Ar commented on post/index.php
> +require('../dbconnect.php');
`require`は、この命令ですでに読み込まれた場合でも読み込むため`require_once`を使用する方が良いです

2020-09-22 02:45 UTC, mayu222 commented on post/index.php
> +            foreach ($posts as $post) :
foreachを上のロジック部分に持ってくると、formタグもforeachの対象になってしまい、何個も投稿エリアが作られてしまうのですが、そういった時はどのように回避したら良いのでしょうか。

2020-09-22 13:53 UTC, n06Ar commented on post/index.php
> +            foreach ($posts as $post) :
方法は下記の二つあり、1を使用し回避すれば良いです。
（2は余談です）

1. ロジック部分（$postsの取得処理の59行目の後ろあたり）で、表示用の変数（配列）を用意し、$postsをforeachで回して、$postsとselect_like_cnt、select_retweet_cnt、select_retweet_cntの取得結果を表示用の変数に格納して、ここでforeachで回す方法
2.  テーブルを結合して、select_like_cnt、select_retweet_cnt、select_retweet_cntのSQLをまとめて実行する方法

1は、foreachを純粋に増やして、ロジックと表示を分離する方法です。
現状のコードから改修がシンプルに実装できますが、不要なループが発生します。
ただ様々な今回はこちらの方が良いです。

2は、データの取得方法をSQLに任せることで、PHPでのデータの加工のロジックをしなくてよくなります。
ただし、SQLが複雑になることや上手くやらないとパフォーマンスが出なくなります。（トータルで見ると現状のロジックよりはパフォーマンスが高いです）
また、文法をDBのカリキュラムで詳細に触れるはずなので、今回は使わない方針で良いです。

2020-09-27 01:17 UTC, n06Ar commented on post/index.php
> +                        <input type="hidden" name="reply_post_id" value="<?php echo h($_REQUEST['res'] ?? ''); ?>" />
`retweet_post_id`もですが、`$_REQUEST['res'] ?? ''`にある`''`を他のリプライのレコードを参照しない値に修正してください。
現状だとinsertする時に`reply_post_id`が`string('')`となるため、intの値が入るべき場所にstringを入れようとして失敗するため投稿することができません。

2020-09-27 03:04 UTC, mayu222 commented on post/index.php
> +                        <input type="hidden" name="reply_post_id" value="<?php echo h($_REQUEST['res'] ?? ''); ?>" />
他のリプライのレコードを参照しない値とはなんでしょうか。
空文字ではなく、数値を指定したら良いのですか？
また、手元だと失敗せずにそのまま投稿が出来てしまいます。

2020-09-27 04:23 UTC, n06Ar commented on post/index.php
> +                        <input type="hidden" name="reply_post_id" value="<?php echo h($_REQUEST['res'] ?? ''); ?>" />
> 空文字ではなく、数値を指定したら良いのですか？ 

`reply_post_id`と`retweet_post_id`は、intでNOT NULLに設定をしていますよね。（以前いただいたDDLより）
それであればint型なので整数しか入らないので整数を指定してください。

> 他のリプライのレコードを参照しない値とはなんでしょうか。

リプライやリツイートを判別するのに`reply_post_id`と`retweet_post_id`は、postsテーブルの`id`を参照している認識です。
その場合、リプライとリツイートをしない新規投稿の場合は、この参照する`id`は**存在しない**`id`を設定する必要があります。
この時の存在しないIDのことが、`他のリプライのレコードを参照しない値`です。

 > また、手元だと失敗せずにそのまま投稿が出来てしまいます。

確認ですが、テーブル定義が変わっていない認識であっていますか？
また、`post/index.php`に下記のコードを追記して（これはコミットしないでください）、`reply_post_id`と`retweet_post_id`の値と型情報をいただけますでしょうか？

2020-09-27 04:35 UTC, n06Ar requested changes
今更ながら大変申し訳ありませんが、気になったところに追加のコメントをしました。

2020-09-27 04:35 UTC, n06Ar commented on post/index.php
> +    if (!empty($_POST['message'])) {
19行目のif文と20行目のif文を分ける必要はないです。
一つにまとめて、下記のようにしてください。
```php
if (!empty($_POST) && !empty($_POST['message')) {
  ...
}

```

2020-09-27 04:35 UTC, n06Ar commented on post/index.php
> +            $retweet->execute([
もし、22行目のSQLが失敗した場合は、こちらはそのまま実行して問題ないでしょうか？

2020-09-27 10:36 UTC, mayu222 commented on post/index.php
> +                        <input type="hidden" name="reply_post_id" value="<?php echo h($_REQUEST['res'] ?? ''); ?>" />
ご回答ありがとうございます。

> intでNOT NULLに設定をしていますよね。

NOT NULLになってそうです。
![image](https://user-images.githubusercontent.com/58901813/94362690-248c5c80-00f8-11eb-9511-bbe939438b41.png)


> post/index.phpに下記のコードを追記して（これはコミットしないでください）、reply_post_idとretweet_post_idの値と型情報をいただけますでしょうか？

すみません、こちらの下記のコードとはどちらのコードの事ですか？

2020-09-28 05:43 UTC, mayu222 commented on post/index.php
> +            $retweet->execute([
どちらも成功しないといけない処理なのでトランザクションを使うように修正しました。

2020-09-28 11:53 UTC, n06Ar commented on post/index.php
> +                        <input type="hidden" name="reply_post_id" value="<?php echo h($_REQUEST['res'] ?? ''); ?>" />
> すみません、こちらの下記のコードとはどちらのコードの事ですか？

申し訳ありません。
下記のコードになります。
```php
var_dump($_POST['reply_post_id']);
var_dump($_POST['retweet_post_id']);
exit;
```
目的としては、それぞれの中にある値の型情報を確認したかった次第です。

ただ、すでにinputの値に0を入れられている改修をしているので、こちらの対応はしなくても良いです。

2020-09-28 12:22 UTC, n06Ar requested changes
LGTMです。
最後にimo的なコメントを付けたので、ご確認をお願いします。

2020-09-28 12:22 UTC, n06Ar commented on functions.php
> +//htmlspecialcharsのショートカット
もし今後FunctionやMethodでコメントする場合は、PHPDocを使うとエディタにもコメントが表示されたり便利なので使ってみると良いです
https://zonuexe.github.io/phpDocumentor2-ja/references/phpdoc/index.html

2020-09-28 12:22 UTC, n06Ar commented on post/index.php
> +    try {
この投稿を取得する一連の処理はfunctionに独立できるので、functionにまとめると良いです。
functionに分離すると、可読性や役割と関心の分離、PHPUnitでの単体テストができるようになる観点でメリットがあるので良いです。

2020-09-29 07:24 UTC, merged